-- Codele database schema (PostgreSQL)
-- Managed by Flyway; JPA uses ddl-auto=validate only.

CREATE TABLE app_users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role       VARCHAR(32) NOT NULL DEFAULT 'USER',
    CONSTRAINT uk_app_users_username UNIQUE (username),
    CONSTRAINT uk_app_users_email UNIQUE (email)
);

CREATE TABLE user_stats (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                     BIGINT NOT NULL,
    puzzles_played              INT NOT NULL DEFAULT 0,
    puzzles_solved              INT NOT NULL DEFAULT 0,
    current_streak              INT NOT NULL DEFAULT 0,
    best_streak                 INT NOT NULL DEFAULT 0,
    perfect_solves              INT NOT NULL DEFAULT 0,
    solved_under25              INT NOT NULL DEFAULT 0,
    solved_under50              INT NOT NULL DEFAULT 0,
    solved_under75              INT NOT NULL DEFAULT 0,
    solved_over75               INT NOT NULL DEFAULT 0,
    total_wrong_guesses         INT NOT NULL DEFAULT 0,
    total_word_guesses          INT NOT NULL DEFAULT 0,
    total_reveal_percent_on_solve DOUBLE PRECISION NOT NULL DEFAULT 0,
    hints_used                  INT NOT NULL DEFAULT 0,
    total_solve_seconds         BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_user_stats_user_id UNIQUE (user_id),
    CONSTRAINT fk_user_stats_user FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE CASCADE
);

CREATE TABLE puzzles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            VARCHAR(255) NOT NULL,
    answer          VARCHAR(255) NOT NULL,
    language        VARCHAR(255) NOT NULL,
    category        VARCHAR(64),
    difficulty      VARCHAR(32),
    code_content    TEXT NOT NULL,
    short_clue      VARCHAR(1024),
    explanation     TEXT,
    scheduled_date  DATE,
    CONSTRAINT uk_puzzles_slug UNIQUE (slug),
    CONSTRAINT uk_puzzles_scheduled_date UNIQUE (scheduled_date)
);

CREATE TABLE puzzle_tags (
    puzzle_id BIGINT NOT NULL,
    tag       VARCHAR(255) NOT NULL,
    PRIMARY KEY (puzzle_id, tag),
    CONSTRAINT fk_puzzle_tags_puzzle FOREIGN KEY (puzzle_id) REFERENCES puzzles (id) ON DELETE CASCADE
);

CREATE TABLE puzzle_attempts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    puzzle_id        BIGINT NOT NULL,
    user_id          BIGINT,
    solved           BOOLEAN NOT NULL,
    reveal_percent   INT NOT NULL,
    wrong_guesses    INT NOT NULL,
    word_guesses     INT NOT NULL,
    hints_used       INT NOT NULL,
    score            INT NOT NULL,
    duration_seconds BIGINT NOT NULL,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_puzzle_attempts_puzzle FOREIGN KEY (puzzle_id) REFERENCES puzzles (id) ON DELETE CASCADE,
    CONSTRAINT fk_puzzle_attempts_user FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE SET NULL
);

CREATE INDEX idx_puzzles_scheduled_date ON puzzles (scheduled_date);
CREATE INDEX idx_puzzle_attempts_user_id ON puzzle_attempts (user_id);
CREATE INDEX idx_puzzle_attempts_puzzle_id ON puzzle_attempts (puzzle_id);
